export const GET_PERSONS_START = "GET_PERSONS_START";
export const GET_PERSONS_SUCCESSFUL = "GET_PERSONS_SUCCESSFUL";
export const GET_PERSONS_ERROR = "GET_PERSONS_ERROR";
export const CLICK_EXIST_IN_PERSON = "CLICK_EXIST_IN_PERSON";
export const CLICK_SPECIES_IN_PERSON = "CLICK_SPECIES_IN_PERSON";
export const CLICK_GENDER_IN_PERSON = "CLICK_GENDER_IN_PERSON";
export const CLICK_NEXT_CHARACTERS_LIST = "CLICK_NEXT_CHARACTERS_LIST";
export const CLICK_PREV_CHARACTERS_LIST = "CLICK_PREV_CHARACTERS_LIST";