export const GET_CHARACTERS_START = "GET_CHARACTERS_START";
export const GET_CHARACTERS_SUCCESSFUL = "GET_CHARACTERS_SUCCESSFUL";
export const GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR";

export const GET_CHARACTER_INFO_START = "GET_CHARACTERS_INFO_START";
export const GET_CHARACTER_INFO_SUCCESSFUL = "GET_CHARACTER_INFO_SUCCESSFUL";
export const GET_CHARACTER_INFO_ERROR = "GET_CHARACTERS_INFO_ERROR";

export const GET_EPISODES_INFO_START = "GET_EPISODES_INFO_START";
export const GET_EPISODES_INFO_SUCCESSFUL = "GET_EPISODES_INFO_SUCCESSFUL";
export const GET_EPISODES_INFO_ERROR = "GET_EPISODES_INFO_ERROR";

export const GET_FILTERED_CHARACTERS = "GET_FILTERED_CHARACTERS";